# buffer list that lives in the tabline
[[plugins]]
repo = 'ap/vim-buftabline'

# Change input mode to English when exiting insert mode
# [[plugins]]
# repo = 'yoshida-m-3/vim-im-select'
# hook_add = '''
#   let g:im_select_default = 'com.google.inputmethod.Japanese.Roman'
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  colorscheme iceberg
'''

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'ap/vim-css-color'

# LSP and other support tools
[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''
  let g:coc_global_extensions = [
  \'coc-explorer',
  \'coc-lists',
  \'coc-git',
  \'coc-tsserver',
  \'coc-styled-components',
  \'coc-json',
  \'coc-yank',
  \]
  if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
    let g:coc_global_extensions += ['coc-prettier']
  endif

  " Go to code navigation.
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

  " Use K to show documentation in preview window.
  nnoremap <silent> K :call ShowDocumentation()<CR>

  function! ShowDocumentation()
    if CocAction('hasProvider', 'hover')
      call CocActionAsync('doHover')
    else
      call feedkeys('K', 'in')
    endif
  endfunction

  " Highlight the symbol and its references when holding the cursor.
  autocmd CursorHold * silent call CocActionAsync('highlight')

  " autocmd CursorHold * silent call ShowDocumentation()

  " coc-lists
  nmap <Leader>lf <Cmd>CocList files<CR>
  nmap <Leader>lm <Cmd>CocList mru<CR>
  nmap <Leader>lg <Cmd>CocList grep<CR>
  nnoremap <silent> <Leader>w  :exe 'CocList -I --normal --input='.expand('<cword>').' words'<CR>
  nnoremap <silent> <Leader>W  :exe 'CocList -I --input='.expand('<cword>').' grep'<CR>

  " coc-explorer
  nmap <Leader>e <Cmd>CocCommand explorer<CR>

  " coc-git
  " set statusline+=%{get(g:,'coc_git_status','')}%{get(b:,'coc_git_status','')}%{get(b:,'coc_git_blame','')}

  " coc-yank
  nnoremap <silent> <Leader>y :<C-u>CocList -A --normal yank<cr>
'''
